services:
  - type: web
    name: skillbridge
    env: node
    region: oregon
    branch: main
    repo: https://github.com/rocxam/SKIL.B.F.git
    buildCommand: cd skillbridge-backend && npm run build
    startCommand: cd skillbridge-backend && npm start
    plan: free
    autoDeploy: true
    envVars: []
