services:
  - type: web
    name: skillbridge
    env: node
    region: oregon
    branch: main
    repo: https://github.com/rocxam/SKIL.B.F.git
    buildCommand: cd skillbridge-backend && npm run build
    startCommand: cd skillbridge-backend && npm run start:prod
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
